CREATE TABLE IF NOT EXISTS performance_cycles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cycle_name VARCHAR(255) NOT NULL,
    review_type ENUM('Quarterly', 'Half-Yearly', 'Annual') NOT NULL,
    description TEXT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    self_review_start DATE NULL,
    self_review_end DATE NULL,
    manager_review_start DATE NULL,
    manager_review_end DATE NULL,
    status ENUM('Draft', 'Scheduled', 'Active', 'Closed') NOT NULL DEFAULT 'Draft',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_cycle_name_dates (cycle_name, start_date, end_date),
    KEY idx_cycle_status (status),
    KEY idx_cycle_dates (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS employee_goals (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    manager_id INT NULL,
    cycle_id INT UNSIGNED NULL,
    goal_title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    goal_type ENUM('KPI', 'KRA', 'OKR', 'SMART Goal') NOT NULL DEFAULT 'KPI',
    measurement_criteria TEXT NULL,
    start_date DATE NULL,
    due_date DATE NOT NULL,
    priority ENUM('Low', 'Medium', 'High', 'Critical') NOT NULL DEFAULT 'Medium',
    weightage DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    target_value VARCHAR(120) NULL,
    achieved_value VARCHAR(120) NULL,
    achievement_percentage DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    status ENUM('Draft', 'Pending Approval', 'Approved', 'In Progress', 'On Track', 'Completed', 'Needs Improvement', 'Closed') NOT NULL DEFAULT 'Draft',
    manager_comment TEXT NULL,
    employee_comment TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_goal_employee_cycle_title (employee_id, cycle_id, goal_title),
    KEY idx_goal_employee (employee_id),
    KEY idx_goal_manager (manager_id),
    KEY idx_goal_cycle (cycle_id),
    KEY idx_goal_status (status),
    KEY idx_goal_due_date (due_date),
    CONSTRAINT fk_perf_goal_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_perf_goal_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_goal_cycle FOREIGN KEY (cycle_id) REFERENCES performance_cycles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS goal_progress (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    goal_id INT UNSIGNED NOT NULL,
    employee_id INT NOT NULL,
    updated_by INT NULL,
    progress_date DATE NOT NULL,
    progress_note TEXT NULL,
    blockers TEXT NULL,
    achievement_percentage DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    status ENUM('On Track', 'At Risk', 'Delayed', 'Completed') NOT NULL DEFAULT 'On Track',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_goal_progress_goal (goal_id),
    KEY idx_goal_progress_employee (employee_id),
    KEY idx_goal_progress_date (progress_date),
    KEY idx_goal_progress_status (status),
    CONSTRAINT fk_perf_progress_goal FOREIGN KEY (goal_id) REFERENCES employee_goals(id) ON DELETE CASCADE,
    CONSTRAINT fk_perf_progress_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_perf_progress_updated_by FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS checkins (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    manager_id INT NULL,
    cycle_id INT UNSIGNED NULL,
    goal_id INT UNSIGNED NULL,
    checkin_date DATE NOT NULL,
    next_checkin_date DATE NULL,
    frequency_type ENUM('Weekly', 'Bi-Weekly', 'Monthly', 'Quarterly', 'Ad-Hoc') NOT NULL DEFAULT 'Weekly',
    progress_summary TEXT NOT NULL,
    achievements TEXT NULL,
    challenges TEXT NULL,
    support_needed TEXT NULL,
    manager_comment TEXT NULL,
    status ENUM('Draft', 'Submitted', 'Reviewed', 'Closed') NOT NULL DEFAULT 'Draft',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_checkin_employee (employee_id),
    KEY idx_checkin_manager (manager_id),
    KEY idx_checkin_cycle (cycle_id),
    KEY idx_checkin_goal (goal_id),
    KEY idx_checkin_date (checkin_date),
    KEY idx_checkin_status (status),
    CONSTRAINT fk_perf_checkin_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_perf_checkin_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_checkin_cycle FOREIGN KEY (cycle_id) REFERENCES performance_cycles(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_checkin_goal FOREIGN KEY (goal_id) REFERENCES employee_goals(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS feedbacks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    reviewer_id INT NULL,
    manager_id INT NULL,
    cycle_id INT UNSIGNED NULL,
    goal_id INT UNSIGNED NULL,
    feedback_type ENUM('Manager', 'Peer', 'Self', 'Recognition', '360') NOT NULL DEFAULT 'Manager',
    feedback_title VARCHAR(255) NULL,
    comments TEXT NOT NULL,
    strengths TEXT NULL,
    improvement_areas TEXT NULL,
    recognition_badge VARCHAR(120) NULL,
    visibility ENUM('Private', 'Employee and Manager', 'Public') NOT NULL DEFAULT 'Employee and Manager',
    status ENUM('Draft', 'Submitted', 'Acknowledged') NOT NULL DEFAULT 'Submitted',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_feedback_employee (employee_id),
    KEY idx_feedback_reviewer (reviewer_id),
    KEY idx_feedback_manager (manager_id),
    KEY idx_feedback_cycle (cycle_id),
    KEY idx_feedback_goal (goal_id),
    KEY idx_feedback_type (feedback_type),
    KEY idx_feedback_status (status),
    CONSTRAINT fk_perf_feedback_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_perf_feedback_reviewer FOREIGN KEY (reviewer_id) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_feedback_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_feedback_cycle FOREIGN KEY (cycle_id) REFERENCES performance_cycles(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_feedback_goal FOREIGN KEY (goal_id) REFERENCES employee_goals(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS self_reviews (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    manager_id INT NULL,
    cycle_id INT UNSIGNED NULL,
    self_rating DECIMAL(4,2) NOT NULL DEFAULT 0.00,
    completion_percentage DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    achievements TEXT NULL,
    strengths TEXT NULL,
    challenges TEXT NULL,
    goal_review TEXT NULL,
    additional_comments TEXT NULL,
    status ENUM('Draft', 'Submitted', 'Reviewed', 'Reopened') NOT NULL DEFAULT 'Draft',
    submitted_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_self_review_employee_cycle (employee_id, cycle_id),
    KEY idx_self_employee (employee_id),
    KEY idx_self_manager (manager_id),
    KEY idx_self_cycle (cycle_id),
    KEY idx_self_status (status),
    CONSTRAINT fk_perf_self_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_perf_self_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_self_cycle FOREIGN KEY (cycle_id) REFERENCES performance_cycles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS manager_reviews (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    reviewer_id INT NULL,
    cycle_id INT UNSIGNED NULL,
    self_review_id INT UNSIGNED NULL,
    technical_skill DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    communication DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    productivity DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    teamwork DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    attendance DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    leadership DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    overall_rating DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    overall_comments TEXT NULL,
    promotion_recommendation ENUM('Strongly Recommended', 'Recommended', 'Hold', 'Not Recommended') NULL,
    increment_recommendation DECIMAL(5,2) NULL,
    status ENUM('Draft', 'Submitted', 'Calibrated', 'Approved') NOT NULL DEFAULT 'Draft',
    submitted_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_manager_review_employee_cycle_reviewer (employee_id, cycle_id, reviewer_id),
    KEY idx_manager_employee (employee_id),
    KEY idx_manager_reviewer (reviewer_id),
    KEY idx_manager_cycle (cycle_id),
    KEY idx_manager_self_review (self_review_id),
    KEY idx_manager_status (status),
    CONSTRAINT fk_perf_manager_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_perf_manager_reviewer FOREIGN KEY (reviewer_id) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_manager_cycle FOREIGN KEY (cycle_id) REFERENCES performance_cycles(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_manager_self_review FOREIGN KEY (self_review_id) REFERENCES self_reviews(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS performance_results (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    manager_id INT NULL,
    cycle_id INT UNSIGNED NULL,
    self_review_id INT UNSIGNED NULL,
    manager_review_id INT UNSIGNED NULL,
    goal_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    checkin_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    feedback_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    attendance_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    self_review_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    manager_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    final_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    final_rating ENUM('Poor', 'Needs Improvement', 'Good', 'Excellent', 'Outstanding') NOT NULL,
    performance_bucket ENUM('Low', 'Medium', 'High', 'Top Talent') NOT NULL DEFAULT 'Medium',
    calibration_note TEXT NULL,
    hr_approved TINYINT(1) NOT NULL DEFAULT 0,
    approved_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_result_employee_cycle (employee_id, cycle_id),
    KEY idx_result_employee (employee_id),
    KEY idx_result_manager (manager_id),
    KEY idx_result_cycle (cycle_id),
    KEY idx_result_self_review (self_review_id),
    KEY idx_result_manager_review (manager_review_id),
    KEY idx_result_rating (final_rating),
    KEY idx_result_score (final_score),
    KEY idx_result_hr_approved (hr_approved),
    CONSTRAINT fk_perf_result_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_perf_result_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_result_cycle FOREIGN KEY (cycle_id) REFERENCES performance_cycles(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_result_self_review FOREIGN KEY (self_review_id) REFERENCES self_reviews(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_result_manager_review FOREIGN KEY (manager_review_id) REFERENCES manager_reviews(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS employee_badges (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    reviewer_id INT NULL,
    cycle_id INT UNSIGNED NULL,
    badge_name VARCHAR(120) NOT NULL,
    badge_code VARCHAR(100) NULL,
    reward_points INT UNSIGNED NOT NULL DEFAULT 0,
    recognition_reason TEXT NULL,
    awarded_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_badge_employee (employee_id),
    KEY idx_badge_reviewer (reviewer_id),
    KEY idx_badge_cycle (cycle_id),
    KEY idx_badge_name (badge_name),
    CONSTRAINT fk_perf_badge_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_perf_badge_reviewer FOREIGN KEY (reviewer_id) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_badge_cycle FOREIGN KEY (cycle_id) REFERENCES performance_cycles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pip_records (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    manager_id INT NULL,
    mentor_id INT NULL,
    cycle_id INT UNSIGNED NULL,
    performance_result_id INT UNSIGNED NULL,
    plan_title VARCHAR(255) NOT NULL,
    issue_summary TEXT NULL,
    expectations TEXT NULL,
    support_plan TEXT NULL,
    mentor_name VARCHAR(150) NULL,
    start_date DATE NULL,
    review_deadline DATE NOT NULL,
    end_date DATE NULL,
    status ENUM('Draft', 'Active', 'Monitoring', 'Successful', 'Closed', 'Failed') NOT NULL DEFAULT 'Draft',
    progress_percentage DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    progress_notes TEXT NULL,
    outcome_summary TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_pip_employee (employee_id),
    KEY idx_pip_manager (manager_id),
    KEY idx_pip_mentor (mentor_id),
    KEY idx_pip_cycle (cycle_id),
    KEY idx_pip_result (performance_result_id),
    KEY idx_pip_status (status),
    KEY idx_pip_deadline (review_deadline),
    CONSTRAINT fk_perf_pip_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_perf_pip_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_pip_mentor FOREIGN KEY (mentor_id) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_pip_cycle FOREIGN KEY (cycle_id) REFERENCES performance_cycles(id) ON DELETE SET NULL,
    CONSTRAINT fk_perf_pip_result FOREIGN KEY (performance_result_id) REFERENCES performance_results(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS performance_settings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(120) NOT NULL,
    setting_value VARCHAR(255) NOT NULL,
    updated_by INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_performance_setting_key (setting_key),
    KEY idx_performance_setting_updated_by (updated_by),
    CONSTRAINT fk_perf_setting_updated_by FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;